a=int(input("enter the Number:"))
b=float(input("Enter the float value:"))
c=input("Enter the String:")
d=True
print(type(a))
print(type(b))
print(type(c))
print(type(d))
e=float(a)
f=int(b)
print("Converted value:",e)
print("converted value:",f)
print(type(e))
print(type(f))