N=input("Enter the Student Name:")
R=input("Enter the student Roll number:")
B=input("Enter the Branch of a Student:")
a=int(input("Enter the Physics Marks:"))
b=(int(input("Enter the Maths Marks:")))
c=int(input("Enter the Social Marks:"))
d=int(input("Enter the Science Marks:"))
e=int(input("Enter the Chemistry Marks:"))
print("physics Marks:",a)
print("Maths marks:",b)
print("social Marks:",c)
print("Science Marks:",d)
print("Chemistry Marks",e)
total=a+b+c+d+e
Average=total/5
percentage=int((total/500)*100)
print(type(N))
print(type(R))
print(type(B))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(total))
print(type(Average))
print(type(percentage)) 
print("Total marks:",total)
print("Average marks:",Average)
print("Percentage:",percentage)
if percentage<75:
    print("The Student failed in the Class")
else:
    print("The Student have passed in the Class")    